apiVersion: v1
kind: Secret
metadata:
  name: it21311772-secrets   # <- match deployment
type: Opaque
data:                             # values MUST be base64-encoded
  MONGO_URI:      bW9uZ29kYitzcnY6Ly91c2VyOnVzZXJAaXQyMTMxMTc3Mi5zbGN0ajhiLm1vbmdvZGIubmV0Lz8=       
  ACCESS_TOKEN_SECRET:    MTY4ZDY1OGUyZjE3NTEyZTRhOTIxZGIxM2QwZmIyZmYzMTBiYTNkNTUwOGIzNjk5ZjAyMDU2YjlmZTQ3NjRhMDhmZjJhMmM1ODRmZmFiZTU4NDZiNWIzYWEzZTAwMWY0MmUzMjE3NjE4MTQ2MzQzNDExZmUxZmFiYWJlOTIzMTk=
  REFRESH_TOKEN_SECRET:    NDU1MTBjYTY3MzYxN2U4YWI0NGU3YjExYWU3MjczMzUzODg3MzY4OWM4MmRmNTYwOTBlYTQ3NWIwODc5ZjM4OWFjOTQ4Y2VkNDNlZGY4YzQ1ZGI0MjhmZWI1MTUyNmZlN2JkOWVkOWI0M2RmZGIwY2EzYmRlODdmODMyMTZhNjY=
