apiVersion: v1
kind: Secret
metadata:
  name: it21894510-secrets       # <- match deployment
type: Opaque
data:                             # values MUST be base64-encoded
  MONGO_URI:              bW9uZ29kYitzcnY6Ly91c2VyOnVzZXJAY2x1c3RlcjAubzFvdHlkci5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjA=
  ACCESS_TOKEN_SECRET:     MTY4ZDY1OGUyZjE3NTEyZTRhOTIxZGIxM2QwZmIyZmYzMTBiYTNkNTUwOGIzNjk5ZjAyMDU2YjlmZTQ3NjRhMDhmZjJhMmM1ODRmZmFiZTU4NDZiNWIzYWEzZTAwMWY0MmUzMjE3NjE4MTQ2MzQzNDExZmUxZmFiYWJlOTIzMTk=
  REFRESH_TOKEN_SECRET:    NDU1MTBjYTY3MzYxN2U4YWI0NGU3YjExYWU3MjczMzUzODg3MzY4OWM4MmRmNTYwOTBlYTQ3NWIwODc5ZjM4OWFjOTQ4Y2VkNDNlZGY4YzQ1ZGI0MjhmZWI1MTUyNmZlN2JkOWVkOWI0M2RmZGIwY2EzYmRlODdmODMyMTZhNjY=
  GOOGLE_CLIENT_ID:        MTYzMDkyOTc5MTY3LTk5YnIwbzc5bWJpOG01Y2V0YnVzbGh1NXQxc2llcjM5LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
  GOOGLE_CLIENT_SECRET:    R09DU1BYLU5OR3pJbkdJbVV1dEpsU1cySl9pZEpUU1lNMzE=
